apiVersion: v1
kind: Service
metadata:
  name: service-frontend-pratica-1
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30007